# Generated by Django 4.1.3 on 2023-02-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecipeDetail",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=32)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient",
                        to="recipe.recipeingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
