# Generated by Django 4.1.3 on 2023-03-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientStatusLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
                ("date", models.DateField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="log",
                        to="ingredient.owningredient",
                    ),
                ),
            ],
        ),
    ]
