# Generated by Django 4.1.3 on 2023-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientStatusLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient", models.CharField(max_length=64)),
                ("quantity", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
    ]
