# Generated by Django 4.1.3 on 2023-03-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredientstatuslog",
            old_name="ingredient",
            new_name="ingredient_name",
        ),
    ]
