# Generated by Django 4.1.3 on 2023-02-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OwnIngredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OwnIngredientDetail",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
                ("quantity_unit", models.CharField(max_length=16)),
                ("expiry_date", models.DateField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="ingredient.owningredient",
                    ),
                ),
            ],
        ),
    ]
