# Generated by Django 4.1.3 on 2023-02-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OwnIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("amount", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kilogram", "Kilogram"),
                            ("gram", "Gram"),
                            ("ounce", "Ounce"),
                            ("pound", "Pound"),
                        ],
                        max_length=12,
                    ),
                ),
                ("expiration_date", models.DateField()),
            ],
            options={
                "verbose_name": "own_ingredients",
                "verbose_name_plural": "own_ingredients",
            },
        ),
    ]
