# Generated by Django 4.1.3 on 2023-02-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="owningredients", table="own_ingredients_info",
        ),
    ]
