# Generated by Django 4.1.3 on 2023-02-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0002_owningredientcategory_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owningredients", old_name="amount", new_name="quantity",
        ),
        migrations.RemoveField(model_name="owningredients", name="category",),
        migrations.DeleteModel(name="OwnIngredientCategory",),
    ]
