# Generated by Django 4.1.3 on 2023-02-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0002_alter_owningredients_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owningredients",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
