# Generated by Django 4.1.3 on 2023-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0003_alter_owningredients_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owningredients", name="amount", field=models.FloatField(),
        ),
    ]
